import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className + " bg-[#FDEEB8]"}>
				<Navbar />
				<Providers>
					{children}
				</Providers>
			</body>
			<footer className="w-full bg-gray-100 mt-auto">
				<div className="max-w-screen-xl mx-auto py-4 px-8">
					<p className="text-center text-gray-500 text-sm">
					© {new Date().getFullYear()} Treehouse. All rights reserved.
					</p>
					<p>Created by Kosh Jama, Matthew Tactacan, Latticha Lerdwichagul & Akeef Mamoon</p>
				</div>
			</footer>
		</html>
	);
}
